### ISSUE TITLE
Throws an error when fishing with no applicable fish

### ISSUE THREAD

**Issue by Ultrajungleboy** [TheDevTec/AmazingFishing#4]
[01:10:08] [Server thread/ERROR]: Could not pass event PlayerFishEvent to AmazingFishing v4.1.1
java.lang.NullPointerException: Cannot invoke "me.devtec.theapi.utils.PercentageList.isEmpty()" because "ff" is null
	at me.devtec.amazingfishing.utils.CatchFish.onCatchRemake(CatchFish.java:225) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor515.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.EntityFishingHook.b(EntityFishingHook.java:460) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.ItemFishingRod.a(ItemFishingRod.java:18) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:379) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:447) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1667) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1160) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[01:10:08] [Server thread/ERROR]: Could not pass event PlayerFishEvent to AmazingFishing v4.1.1
java.lang.NullPointerException: Cannot invoke "me.devtec.theapi.utils.PercentageList.isEmpty()" because "ff" is null
	at me.devtec.amazingfishing.utils.CatchFish.onCatch(CatchFish.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor514.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.EntityFishingHook.b(EntityFishingHook.java:460) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.ItemFishingRod.a(ItemFishingRod.java:18) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:379) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:447) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1667) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1191) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1184) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1160) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-2830324]
	at java.lang.Thread.run(Thread.java:832) [?:?]

I fixed this on the clone I have by adding this to the line just above
			
item.remove();
				PercentageList<Fish> ff = generateRandom(e.getPlayer(), loc.getBlock().getBiome(),
						loc.getWorld().hasStorm(), loc.getWorld().isThundering(), loc.getWorld().getTime());
				if(ff == null) {
					e.getPlayer().sendMessage("There's §cno fish §rhere!");
					return;
				}
				else if(ff.isEmpty()) {
					return;
				}

**Comment by Straikerinos** [comment]
```
item.remove();
PercentageList ff = generateRandom(e.getPlayer(), loc.getBlock().getBiome(),
loc.getWorld().hasStorm(), loc.getWorld().isThundering(), loc.getWorld().getTime());
if(ff == null ||ff.isEmpty()) {
  e.getPlayer().sendMessage("There's §cno fish §rhere!");
  return;
}
...
```
@Houska02

**Comment by TheDevTec** [comment]
It is fixed now. If there is no fish, you will catch Junk
